version: '3'

services:
  proxysql:
    image: proxysql/proxysql:latest
    ports:
      - "6033:6033"
      - "6032:6032"
    volumes:
      - ./config/proxysql:/etc/proxysql
    environment:
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=admin
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    depends_on:
      - db1
      - db2
    networks:
      - n1

  db1:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=my_database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - /var/lib/db1:/var/lib/mysql
    networks:
      - n1

  db2:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=my_database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - /var/lib/db2:/var/lib/mysql
    networks:
      - n1

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - n1

networks:
  n1:
    driver: bridge
