version: '3'

services:
  mongo1:
    container_name: mongo1
    image: mongo:4.4
    volumes:
      - ~/mongors/data1:/data/db
      - ./rs-init.sh:/scripts/rs-init.sh
    networks:
      - mongors-network
      - n1
    ports:
      - 27021:27017
    links:
      - mongo2
      - mongo3
    restart: always
    entrypoint:
      [
        "/usr/bin/mongod",
        "--quiet",
        "--bind_ip_all",
        "--replSet",
        "dbrs"
      ]
  mongo2:
    container_name: mongo2
    image: mongo:4.4
    volumes:
      - ~/mongors/data2:/data/db
    networks:
      - mongors-network
    ports:
      - 27022:27017
    restart: always
    entrypoint:
      [
        "/usr/bin/mongod",
        "--quiet",
        "--bind_ip_all",
        "--replSet",
        "dbrs"
      ]
  mongo3:
    container_name: mongo3
    image: mongo:4.4
    volumes:
      - ~/mongors/data3:/data/db
    networks:
      - mongors-network
    ports:
      - 27023:27017
    restart: always
    entrypoint:
      [
        "/usr/bin/mongod",
        "--quiet",
        "--bind_ip_all",
        "--replSet",
        "dbrs"
      ]

  rabbitmq1:
    container_name: rabbitmq1
    image: "rabbitmq:3-management"
    restart: on-failure
    hostname: rabbitmq1
    volumes:
      - rmq-1:/var/lib/rabbitmq
      - ./rmq-conf/rabbitmq1/:/config/
    env_file:
      - rmq-cluster.env
    environment:
      - RABBITMQ_NODENAME=rabbitmq1
      - RABBITMQ_CONFIG_FILE=/config/rabbitmq
    ports:
      - "5672"
      - "15672:15672"
    networks:
      - n1

  rabbitmq2:
    container_name: rabbitmq2
    image: "rabbitmq:3-management"
    restart: on-failure
    hostname: rabbitmq2
    volumes:
      - rmq-2:/var/lib/rabbitmq
      - ./rmq-conf/rabbitmq2/:/config/
    environment:
      - RABBITMQ_NODENAME=rabbitmq2
      - RABBITMQ_CONFIG_FILE=/config/rabbitmq
    env_file:
      - rmq-cluster.env
    ports:
      - "5672"
      - "15673:15672"
    networks:
      - n1

  rabbitmq3:
    container_name: rabbitmq3
    image: "rabbitmq:3-management"
    restart: on-failure
    hostname: rabbitmq3
    volumes:
      - rmq-3:/var/lib/rabbitmq
      - ./rmq-conf/rabbitmq3/:/config/
    environment:
      - RABBITMQ_NODENAME=rabbitmq3
      - RABBITMQ_CONFIG_FILE=/config/rabbitmq
    env_file:
      - rmq-cluster.env
    ports:
      - "5672"
      - "15674:15672"
    networks:
      - n1

  gateway-service-1:
    container_name: api1
    build:
      context: gateway-service
    ports:
      - "3000:3000"
    env_file:
      - rmq.env
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - n1
    depends_on:
      - rabbitmq1
      - rabbitmq2

  gateway-service-2:
    container_name: api2
    build:
      context: gateway-service
    ports:
      - "3001:3000"
    env_file:
      - rmq.env
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - n1

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    networks:
       - n1

  data-access-service-1:
    container_name: crud1
    build:
      context: data-access-service
    ports:
      - "3002:3000"
    env_file:
      - rmq.env
      - mongo.env
    networks:
      - n1

  data-access-service-2:
    container_name: crud2
    build:
      context: data-access-service
    ports:
      - "3003:3000"
    env_file:
      - rmq.env
      - mongo.env
    networks:
      - n1

networks:
  n1:
    driver: bridge
  mongors-network:
    driver: bridge

volumes:
  rmq-1:
    driver: local
  rmq-2:
    driver: local
  rmq-3:
    driver: local
  redis:
    driver: local